title       = "steam"
baseURL     = "https://steamstore-cli.tamnd.com/"
description = "Steam store games and search CLI"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/steamstore-cli"
